// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./../src/components/AppButton.vue')['default']
    Button: typeof import('../src/components/AppButton.vue')['default']
    Carousel: typeof import('./../src/components/Carousel.vue')['default']
    Footer: typeof import('./../src/components/Footer.vue')['default']
    LocationCard: typeof import('./../src/components/LocationCard.vue')['default']
    Navigation: typeof import('./../src/components/Navigation.vue')['default']
    PopularDestinationCard: typeof import('./../src/components/PopularDestinationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuccessCard: typeof import('./../src/components/SuccessCard.vue')['default']
  }
}
